{
 "title": "Spring Boot Observability 2",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_count[1m]))",
     "legendFormat": "{{method}}--{{uri}}"
    }
   ]
  },
  {
   "title": "Request Rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(method, uri) (rate(http_server_requests_count[1m])))"
    }
   ]
  },
  {
   "title": "Request Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_sum[1m])) / sum by(method, uri) (rate(http_server_requests_count[1m]))",
     "legendFormat": "{{method}}--{{uri}}"
    }
   ]
  },
  {
   "title": "Top-10-latencies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum by(method, uri) (rate(http_server_requests_sum[1m])) / sum by(method, uri) (rate(http_server_requests_count[1m])))"
    }
   ]
  },
  {
   "title": "90th-percentile-latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(le, method, uri) (rate(http_server_requests_bucket[1m]))",
     "legendFormat": "{{method}} -- {{uri}}"
    }
   ]
  }
 ]
}